CLASSFILES = AliasMethodRandomGenerator.class BST.class BSTFactory.class RuntimeAnalyzer.class SplayTree.class TestingHarness.class WeightBalancedTree.class SplayTreeNode.class WBTNode.class

all: $(CLASSFILES)

AliasMethodRandomGenerator.class: AliasMethodRandomGenerator.java
	javac AliasMethodRandomGenerator.java

BST.class: BST.java
	javac BST.java

BSTFactory.class: BSTFactory.java
	javac BSTFactory.java

RuntimeAnalyzer.class: RuntimeAnalyzer.java
	javac RuntimeAnalyzer.java

SplayTree.class: SplayTree.java
	javac SplayTree.java

SplayTreeNode.class: SplayTreeNode.java
	javac SplayTreeNode.java

TestingHarness.class: TestingHarness.java
	javac TestingHarness.java

WeightBalancedTree.class: WeightBalancedTree.java
	javac WeightBalancedTree.java

WBTNode.class: WBTNode.java
	javac WBTNode.java

clean:
	rm -f *~ *.class

