CLASSFILES = LazyBinomialHeap.class MeldableLinkedList.class LinkedListNode.class PS4Driver.class LCRSTree.class LCRSNode.class

all: $(CLASSFILES)

LazyBinomialHeap.class: LazyBinomialHeap.java
	javac -Xlint:unchecked LazyBinomialHeap.java

MeldableLinkedList.class: MeldableLinkedList.java
	javac -Xlint:unchecked MeldableLinkedList.java

LinkedListNode.class: LinkedListNode.java
	javac -Xlint:unchecked LinkedListNode.java

PS4Driver.class: PS4Driver.java
	javac -Xlint:unchecked PS4Driver.java

LCRSTree.class: LCRSTree.java
	javac -Xlint:unchecked LCRSTree.java

LCRSNode.class: LCRSNode.java
	javac -Xlint:unchecked LCRSNode.java
clean:
	rm -f *~ *.class
