CLASSFILES = LazyBinomialHeap.class MeldableLinkedList.class LinkedListNode.class PS4Driver.class LCRSTree.class LCRSNode.class

all: $(CLASSFILES)

LazyBinomialHeap.class: LazyBinomialHeap.java
	javac LazyBinomialHeap.java

MeldableLinkedList.class: MeldableLinkedList.java
	javac MeldableLinkedList.java

LinkedListNode.class: LinkedListNode.java
	javac LinkedListNode.java

PS4Driver.class: PS4Driver.java
	javac PS4Driver.java

LCRSTree.class: LCRSTree.java
	javac LCRSTree.java
	
LCRSNode.class: LCRSNode.java
	javac LCRSNode.java
clean:
	rm -f *~ *.class
