CLASSFILES = LazyBinomialHeap.class MeldableLinkedList.class LinkedListNode.class PS4Driver.class

all: $(CLASSFILES)

LazyBinomialHeap.class: LazyBinomialHeap.java
	javac LazyBinomialHeap.java

MeldableLinkedList.class: MeldableLinkedList.java
	javac MeldableLinkedList.java

LinkedListNode.class: LinkedListNode.java
	javac LinkedListNode.java

PS4Driver.class: PS4Driver.java
	javac PS4Driver.java
clean:
	rm -f *~ *.class
